# templates/deployment-dbservice.yaml
{{- if .Values.dbService }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.dbService.name }}
spec:
  replicas: {{ .Values.dbService.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.dbService.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.dbService.name }}
        app.kubernetes.io/component: {{ .Values.dbService.name }}
    spec:
      containers:
        - name: {{ .Values.dbService.name }}
          image: {{ .Values.dbService.image | quote }}
          ports:
            - containerPort: {{ .Values.dbService.service.targetPort }} # 3000
          resources:
            {{- toYaml .Values.dbService.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ .Values.dbService.name }}-config
            - secretRef:
                name: {{ .Values.dbService.secretName }}
{{- if .Values.dbService.conjurSecretName }}
            - secretRef:
                name: {{ .Values.dbService.conjurSecretName }}
{{- end }}
          readinessProbe:
            httpGet:
              path: /status
              port: {{ .Values.dbService.service.targetPort }}
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /status
              port: {{ .Values.dbService.service.targetPort }}
            initialDelaySeconds: 30
            periodSeconds: 20
            failureThreshold: 3
{{- end }}
