# templates/routes-and-ingresses.yaml

{{- /* Crea la Ruta/Ingress para el servicio 'adminApp' */}}
{{- if and .Values.adminApp .Values.adminApp.service.enabled .Values.adminApp.ingress.enabled }}
  {{- if .Values.adminApp.ingress.isOpenshiftRoute }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.adminApp.name }}
  annotations:
    haproxy.router.openshift.io/hsts_header: "max-age=31536000;includeSubDomains"
spec:
  {{- with .Values.adminApp.ingress.host }}
  host: {{ . }}
  {{- end }}
  to:
    kind: Service
    name: {{ .Values.adminApp.name }}
  port:
    targetPort: http  # nombre del puerto del Service
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  {{- else }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.adminApp.name }}
spec:
  rules:
    - {{- with .Values.adminApp.ingress.host }}
      host: {{ . }}
      {{- end }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.adminApp.name }}
                port:
                  name: http  # nombre del puerto del Service
  {{- end }}
{{- end }}

{{- /* Crea la Ruta/Ingress para el servicio 'mainService' */}}
{{- if and .Values.mainService .Values.mainService.service.enabled .Values.mainService.ingress.enabled }}
  {{- if .Values.mainService.ingress.isOpenshiftRoute }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.mainService.name }}
  annotations:
    haproxy.router.openshift.io/hsts_header: "max-age=31536000;includeSubDomains"
spec:
  {{- with .Values.mainService.ingress.host }}
  host: {{ . }}
  {{- end }}
  to:
    kind: Service
    name: {{ .Values.mainService.name }}
  port:
    targetPort: http  # nombre del puerto del Service
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  {{- else }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.mainService.name }}
spec:
  rules:
    - {{- with .Values.mainService.ingress.host }}
      host: {{ . }}
      {{- end }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.mainService.name }}
                port:
                  name: http  # nombre del puerto del Service
  {{- end }}
{{- end }}
